### ISSUE TITLE
Filter by tags doesnt work

### ISSUE THREAD

**Issue by prakash03** [up-for-grabs/up-for-grabs.net#1184]
Filter by tags doesn't seem to work.

Steps to reproduce:
* Browse for any language in the 'Filter by tags:' section
* choose the language from the suggestions

Expected behavior:
* If there are any projects available they should show up

Actual behavior:
* No results show up

**Comment by prakash03** [comment]
Could any of the maintainers confirm if this issue can be approved? I would love to work on it!

**Comment by ritwik12** [comment]
@prakash03 Hey, this used to work properly. @shiftkey made some changes to the code. Maybe it's as expected for now. It will be best if he'll tell about this.

**Comment by shiftkey** [comment]
@prakash03 the problem is with the URL that gets updated after choosing an item in the list.

If you check the URL you'll see it looks like this:

<img width="384" src="https://user-images.githubusercontent.com/359239/54166047-19a0a700-4442-11e9-9880-8b29a80f5b12.png">

When you click on a tag link you'll see the URL looks a bit different:

<img width="397" src="https://user-images.githubusercontent.com/359239/54166091-4fde2680-4442-11e9-9c63-4523d18e1ad3.png">

This one should work, and that's what we should be looking for.

**Comment by prakash03** [comment]
Thanks for the update @shiftkey! I will work on it.

**Comment by itaigilo** [comment]
Opened a PR fixing this: #1196.
