### ISSUE TITLE
Tags are too similar

### ISSUE THREAD

**Issue by stephnr** [up-for-grabs/up-for-grabs.net#211]
Perhaps we can have the tags be different colors based on context. I would say up-for-grabs should be green, where as 'jump-in' can be a separate color.

**Comment by shiftkey** [comment]
I don't want to be too proscriptive here with the labels - we left it up to each project what they want to call their label. But colours and visual things could definitely be better - perhaps we could use a different colour for the label and tags?

<img width="673" alt="screen shot 2015-07-28 at 10 39 29 am" src="https://cloud.githubusercontent.com/assets/359239/8921453/f9f6f4b2-3514-11e5-9267-827e75d7ae06.png">

**Comment by stephnr** [comment]
Yes! I totally agree @shiftkey

**Comment by shiftkey** [comment]
If we wanted to integrate with GitHub better, we could get the colour associated with the label _for each project_ through the API: https://developer.github.com/v3/issues/labels/#get-a-single-label

``` json
{
  "url": "https://api.github.com/repos/octocat/Hello-World/labels/bug",
  "name": "bug",
  "color": "f29513"
}
```

But I think this should be done through an external data API we manage to support caching, rather than exhaust the user's anonymous API limit (which we're kind of already doing).
