### ISSUE TITLE
Question: Add more than one repository to a project

### ISSUE THREAD

**Issue by etabakov** [up-for-grabs/up-for-grabs.net#601]
Hey guys, 
Our product is spread among multiple repositories in a single GitHub organisation. Is it possible to show somehow different repositories under a single project? Or at least accumulate the numbers from several repos?

Thanks!

**Comment by aph3rson** [comment]
At present, there isn't a method to do this, add together numbers from different sources.

Previously, what others have done is have the `up-for-grabs/link` URL point to a search of relevant (i.e. open/tagged) issues for projects in that organization. Unfortunately, that doesn't allow for issue counts to be updated. Alternatively, you could create a project for each repo in your organization, which some have done. Perhaps add a bit to the `desc` field mentioning the project.

This is somewhat similar in nature to #344 and #578, though this would mean a different project URL, instead of a different tag.

**Comment by shiftkey** [comment]
@etabakov here's an example of doing an org-level link: https://github.com/up-for-grabs/up-for-grabs.net/blob/8b6647926010f199de407211e8e0e2875830f175/_data/projects/ipfs.yml#L18

For other discussions, let's add it to #344 or #578
