### ISSUE TITLE
Order in "filter by name" option

### ISSUE THREAD

**Issue by ghost** [up-for-grabs/up-for-grabs.net#945]
Ascending order by project name would be more user friendly.

**Comment by ritwik12** [comment]
@drashti4 Yes, that will be a good thing to add. Please feel free to send a PR.

**Comment by ghost** [comment]
I run this project locally and I got ordered name without changing JS or any file. Is this expected output?
![screenshot 3](https://user-images.githubusercontent.com/9081004/41188083-d35b00c6-6b7d-11e8-90a0-181e363ae393.png)

**Comment by ritwik12** [comment]
@drashti4 That must be, 
Also, I thought that you were talking about projects too. can you try to filter the projects too by name?

**Comment by ghost** [comment]
I was talking about order project name in search bar where I'm already getting correct output in local without changing code but its not showing in site. Regarding to project I think those project which has more PR should be on top rather than alphabetical order, what do you think?

**Comment by ritwik12** [comment]
@drashti4 Not PR, We can do it according to issue count. Both ways are fine.With alphabetical order every project is treated equal. What I am afraid is that if we sort according to issue count then people will look only the top projects, which will ignore the sole purpose of the website i.e to host projects so that new open source contributors can find projects to start with. I think suggestions from others are also needed on this. What do you think?

**Comment by ghost** [comment]
Getting more input is always good. I believe right now it's completely random order.

**Comment by ritwik12** [comment]
@drashti4 Yes, it is. Until then you can submit PR for sorting search field. The one mentioning this issue.

**Comment by ranjan-purbey** [comment]
IMO having a feature to sort projects according to a few fields (like name, date added, recent activity, number of open issues etc.) will be a great feature to have and ease new collaborators to find projects.

**Comment by juliankrieger** [comment]
Can be closed when https://github.com/up-for-grabs/up-for-grabs.net/pull/1092 is merged

**Comment by ritwik12** [comment]
Fixed!!
